// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEHOPuc-5AeRMFmsiwTIAz_PnZdbRt0bI',
    appId: '1:694456373449:web:6c9978561ac4c6af5bfd18',
    messagingSenderId: '694456373449',
    projectId: 'ecom-46d16',
    authDomain: 'ecom-46d16.firebaseapp.com',
    storageBucket: 'ecom-46d16.appspot.com',
    measurementId: 'G-BWRER4ER0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoacnDl11mygfOnBxT0bcHSn9sXvrxb_w',
    appId: '1:694456373449:android:642a1c614fd34cd75bfd18',
    messagingSenderId: '694456373449',
    projectId: 'ecom-46d16',
    storageBucket: 'ecom-46d16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA9Xxg3oaaErZM4FMgIYxNJg77niiRGSY',
    appId: '1:694456373449:ios:8e85771dd69ce6795bfd18',
    messagingSenderId: '694456373449',
    projectId: 'ecom-46d16',
    storageBucket: 'ecom-46d16.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA9Xxg3oaaErZM4FMgIYxNJg77niiRGSY',
    appId: '1:694456373449:ios:8e85771dd69ce6795bfd18',
    messagingSenderId: '694456373449',
    projectId: 'ecom-46d16',
    storageBucket: 'ecom-46d16.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEHOPuc-5AeRMFmsiwTIAz_PnZdbRt0bI',
    appId: '1:694456373449:web:c2602c890d219b165bfd18',
    messagingSenderId: '694456373449',
    projectId: 'ecom-46d16',
    authDomain: 'ecom-46d16.firebaseapp.com',
    storageBucket: 'ecom-46d16.appspot.com',
    measurementId: 'G-7Q99JLF8FR',
  );
}
